
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-ZipCode","number":24,"title":"Tony ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-4/pull/24"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-Jokes-Controller","number":23,"title":"Add Jokes Controller and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-4/pull/23"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-PublicHoliday","number":22,"title":"Add PublicHolidayService and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-4/pull/22"},{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-Jokes","number":21,"title":"Add Jokes Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-4/pull/21"},{"author":{"id":"U_kgDOBX3Lkw","is_bot":false,"login":"ElijahCanderson","name":""},"headRefName":"Eli","number":20,"title":"LocationQueryService, Service Setup and Tests with complete coverage.","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-4/pull/20"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-University-Controller","number":19,"title":"Add University Controller and Tests ","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-4/pull/19"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-University","number":18,"title":"Add University Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-4/pull/18"}]
